#!/bin/bash

tty=
tty -s && tty=--tty
docker run \
    $tty \
    --rm \
    --init \
    --net host \
        --user $(id -u):$(id -g) \
        --volume $HOME:$HOME:ro \
        --volume $HOME/.composer:/.composer:rw \
        --volume $(pwd):$(pwd) \
        --workdir $(pwd) \
    --workdir $(pwd) \
    composer:latest composer "$@"