FROM php:7.2-cli-alpine

WORKDIR /app

RUN set -ex \
    && apk --no-cache add postgresql-dev git \
    && docker-php-ext-install pdo pdo_pgsql \
    && git clone https://github.com/PlaylistScience/medley.git

ENTRYPOINT ["nohup", "php", "-S", "0.0.0.0:8080", "-t", "public"]